indication_raw_updater:
  name: Indication Raw Updater
  description: PetroElectroSbyt Raw Indication Updater (publishing to PES API as is)
  target:
  fields:
    peak_value:
      name: Peak Value
      description: Energy Meter New Peak Value
      required: true
      example: 7890
    offpeak_value:
      name: Offpeak Value
      description: Energy Meter New Offpeak Value
      required: true
      example: 1240
indication_incremental_updater:
  name: Indication Incremental Updater
  description: PetroElectroSbyt Incremental Indication Updater (publishing to PES API as current + increment)
  target:
  fields:
    peak_value:
      name: Peak Value
      description: Energy Meter Incremental Peak Value
      required: true
      example: 100
    offpeak_value:
      name: Offpeak Value
      description: Energy Meter Incremental Offpeak Value
      required: true
      example: 50